// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anmzxbljzkyuvrrarqtu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFubXp4Ymxqemt5dXZycmFycXR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExNzEwODQsImV4cCI6MjA3Njc0NzA4NH0.aYLKA24Z9H113KbXM9rjYgjMTd7Ukhmn4esXmK_JNoo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});