// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqsgauziwigazvatcial.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxc2dhdXppd2lnYXp2YXRjaWFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTY1MjgsImV4cCI6MjA2ODQzMjUyOH0.Pwd1DWAnT0U1MJI3NFDVjw-1PJOgWIkGeClSxxDpsvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});